# ========================
# DATABASE (PostgreSQL)
# ========================
spring.datasource.url=${jdbc:postgresql://dpg-d720g4cr85hc73aqc2q0-a.oregon-postgres.render.com:5432/stride_db_15dv}
spring.datasource.username=${stride_db_15dv_user}
spring.datasource.password=${qHkGvpPLKsTnVaswcHxUYoBX9Bq8wuSi}
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA
# ========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ========================
# DISABLE H2
# ========================
spring.h2.console.enabled=false

# ========================
# JWT
# ========================
app.jwt.secret=${JWT_SECRET:StrideAI-Super-Secret-256bit-Key-2026!!}

# ========================
# CORS
# ========================
app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:3000}

# ========================
# SERVER
# ========================
server.port=${PORT:8080}